# Generated by Django 6.0.7 on 2026-07-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetails',
            name='complainant_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintdetails',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintdetails',
            name='police_station',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
