# Generated by Django 6.0.6 on 2026-07-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_app', '0002_complaintdetails_complainant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaintdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='complaintdetails',
            name='id_proof',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
