# Generated by Django 6.0.7 on 2026-07-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_app', '0003_complaintdetails_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetails',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
