# Generated by Django 6.0.7 on 2026-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_app', '0004_complaintdetails_id_proof_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetails',
            name='language_preference',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], default='English', help_text='Preferred language for FIR drafting', max_length=20),
        ),
    ]
